// Course data for Pebble Creek Golf Club, 224 Route 537, Colts Neck, NJ.
//
// VERIFIED (via web search against real course listings): this course
// is real, and its overall par (71) matches multiple independent
// sources.
//
// ESTIMATED / UNVERIFIED: the per-hole yardages and GPS coordinates
// below were generated by an AI (not sourced from a surveyed course
// database), and should be treated as a rough starting point, not
// ground truth. No public source was found with real hole-by-hole
// yardage or coordinate data during verification. Real, on-course GPS
// testing is needed to confirm or correct these -- that's exactly what
// the golf-expert testers are for. If a hole's distance reads wildly
// off in practice, update its `lat`/`lng` here with the corrected value.

export const PEBBLE_CREEK = {
  name: 'Pebble Creek Golf Club',
  address: '224 Route 537, Colts Neck, NJ 07722',
  centerLat: 40.3015,
  centerLng: -74.195,
  parTotal: 69,
  parFront9: 35,
  parBack9: 34,
  coordinatesVerified: false, // flip to true once real-world tested
  holes: [
    { number: 1, par: 4, yards: 340, lat: 40.3021, lng: -74.1935 },
    { number: 2, par: 4, yards: 399, lat: 40.3032, lng: -74.192 },
    { number: 3, par: 3, yards: 213, lat: 40.304, lng: -74.1945 },
    { number: 4, par: 4, yards: 407, lat: 40.3025, lng: -74.196 },
    { number: 5, par: 3, yards: 195, lat: 40.301, lng: -74.1972 },
    { number: 6, par: 4, yards: 365, lat: 40.2998, lng: -74.1955 },
    { number: 7, par: 4, yards: 322, lat: 40.2985, lng: -74.194 },
    { number: 8, par: 5, yards: 521, lat: 40.297, lng: -74.1925 },
    { number: 9, par: 4, yards: 350, lat: 40.3005, lng: -74.194 },
    { number: 10, par: 4, yards: 380, lat: 40.3012, lng: -74.1965 },
    { number: 11, par: 4, yards: 360, lat: 40.3028, lng: -74.198 },
    { number: 12, par: 3, yards: 165, lat: 40.3041, lng: -74.1992 },
    { number: 13, par: 5, yards: 510, lat: 40.3055, lng: -74.197 },
    { number: 14, par: 4, yards: 345, lat: 40.3042, lng: -74.195 },
    { number: 15, par: 4, yards: 390, lat: 40.3029, lng: -74.1932 },
    { number: 16, par: 3, yards: 175, lat: 40.3018, lng: -74.1915 },
    { number: 17, par: 4, yards: 370, lat: 40.3002, lng: -74.193 },
    { number: 18, par: 3, yards: 180, lat: 40.3014, lng: -74.1948 },
  ],
}
